import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import getTranslations from "../i18n-next";
import { TLocale } from "../components/interfaces/global.interfaces";

const inter = Inter({ subsets: ["latin"] });

export interface LocaleParams {
  locale: TLocale;
}
interface ParamsType extends LocaleParams {}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params: { locale },
  children,
}: {
  params: ParamsType;
  children: React.ReactNode;
}) {
  const { resources, dir } = await getTranslations(locale);
  console.log(dir);

  return (
    <html lang={locale} dir={dir}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
